name: Terraform workflow

on: push

jobs:
    apply:
        name: 'Terraform apply'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout rep
              uses: actions/checkout@v3

            - name: Terraform setup
              uses: hashicorp/setup-terraform@v3

            - name: Terraform init
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: terraform init

            - name: Terraform apply
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: terraform apply -auto-approve